resources:
- repo: self
queue:
  name: Hosted Linux Preview
  condition: succeeded()
#Your build pipeline references the ‘BuildConfiguration’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
steps:
- task: DotNetCoreInstaller@0
  displayName: Use .NET Core sdk 2.1.301
  inputs:
    version: 2.1.301

- task: DotNetCoreCLI@2
  displayName: dotnet restore
  inputs:
    command: restore

- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    arguments: '--no-restore --configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: dotnet publish
  inputs:
    command: publish
    publishWebProjects: false
    arguments: '--no-build --configuration $(BuildConfiguration) /p:PublishChromeDriver=true'
    zipAfterPublish: false

- task: CopyFiles@2
  displayName: Copy Files to artifact staging directory
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/bin/$(BuildConfiguration)/**/publish/**'
    TargetFolder: '$(build.artifactstagingdirectory)'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  displayName: Publish artifacts to drop folder
